# Generated by Django 4.2.3 on 2023-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chat_name',
            field=models.CharField(default='New Chat', max_length=409600, null=True),
        ),
    ]
