# Generated by Django 4.2.3 on 2023-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faiss_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(blank=True, max_length=256, verbose_name='文件名')),
                ('text', models.FileField(blank=True, null=True, upload_to='FAISS_Data', verbose_name='txt文件')),
                ('categories', models.CharField(blank=True, max_length=128, null=True, verbose_name='分类')),
            ],
        ),
    ]
